database:
  user: root
  password: zyb629225
  server: 47.96.230.189
  port: 3306
  dbName: yanhai

# 运行环境 开发dev 部署prod
runenv: dev

# 不同环境的存储路径
picpath:
  devpath: ./testpic/
  prodpath: /home/yanhaipic/

port: 8080